### ISSUE TITLE
Cannont require package via composer

### ISSUE THREAD

**Issue by akeinhell** [jaspervdm/pogoprotos-php#13]
`PHP Warning:  require(../PokeGOAPI-PHP/vendor/composer/../jaspervdm/pogoprotos-php/src/protoc-gen-php/protocolbuffers.inc.php): failed to open stream: No such file or directory in ../PokeGOAPI-PHP/vendor/composer/autoload_real.php on line 66`

**Comment by akeinhell** [comment]
it only on tagged 0.0.2 version :smiley: 
please add new tag

**Comment by jaspervdm** [comment]
We will add a tagged version soon. However we are looking into switching to a different generator for the PHP files, since the current one gives us many issues, see the test-protobuf branch and the various PRs

**Comment by jaspervdm** [comment]
A new version has been added.
