### ISSUE TITLE
how can i use this

### ISSUE THREAD

**Issue by howedeng** [jaspervdm/pogoprotos-php#14]
how can i login with google,and select my pokemon info?

**Comment by DrDelay** [comment]
First of all, the login (Google or Ptc) is not part of this repository. You have to authenticate at certain endpoints using "plain" HTTP-requests.

Example with Ptc (`client` is a Guzzle-Client, validation removed to make it shorter):

``` php
    const PTC_LOGIN_URL = 'https://sso.pokemon.com/sso/login?service=https%3A%2F%2Fsso.pokemon.com%2Fsso%2Foauth2.0%2FcallbackAuthorize';
    const PTC_OAUTH_URL = 'https://sso.pokemon.com/sso/oauth2.0/accessToken';
    const PTC_OAUTH_CLIENT_ID = 'mobile-app_pokemon-go';
    const PTC_OAUTH_REDIRECT = 'https://www.nianticlabs.com/pokemongo/error';
    const PTC_OAUTH_CLIENT_SECRET = 'w8ScCUXJQc6kXKw8FiOhd8Fixzht18Dq3PEVkUCP5ZPxtgyWsbTvWHFLm2wNY0JR';

(...)

        $session = json_decode($this->client->get(static::PTC_LOGIN_URL)->getBody());

        $login = $this->client->post(static::PTC_LOGIN_URL, [
            'form_params' => [
                'lt' => $session->lt,
                'execution' => $session->execution,
                '_eventId' => 'submit',
                'username' => $this->username,
                'password' => $this->password,
            ],
        ]);
        $ticketRedirect = $login->getHeaderLine('Location');
        (...)
        parse_str(parse_url($ticketRedirect, PHP_URL_QUERY), $queryParts);
        (...)
        $ticket = $queryParts['ticket'];

        $token = $this->client->post(static::PTC_OAUTH_URL, [
            'form_params' => [
                'client_id' => static::PTC_OAUTH_CLIENT_ID,
                'redirect_uri' => static::PTC_OAUTH_REDIRECT,
                'client_secret' => static::PTC_OAUTH_CLIENT_SECRET,
                'grant_type' => 'refresh_token',
                'code' => $ticket,
            ],
        ]);
        parse_str($token->getBody(), $tokenParts);
        (...)
        // $tokenParts['access_token'] contains the token
        // $tokenParts['expires'] its lifetime in seconds, if you want to cache it
```

The token will be something like `TGT-4426529-bj1ab0gqu2lNIexyyZruj5tkoBZCV67dLEEaR2cKIqzTYwBg2q-sso.pokemon.com`.

From Google you'll need an so called `id_token`, this is a considerably longer one. There are many examples for Google OAuth in the web (the [playground](https://developers.google.com/oauthplayground/) is cool). You may look at [this](https://github.com/jaspervdm/pogoapi-php/blob/master/src/Session/GoogleSession.php) (not tested) for a basic authentication flow with username/password, or NicklasWallgren/PokemonGoAPI-PHP#54 for an OAuth solution.

Now, coming to the contents of this repo, I'd suggest you to use the "new" Protobuf-plugin as discussed in #8 , it seems to be a lot cleaner, without having the fiddle in the vendors code to fix some bugs. I have it required like this in my _composer.json_ until it is officially merged and tagged: 
`"jaspervdm/pogoprotos-php": "dev-test-protobuf#c9ac6ddee52217e75b142fae355250c5edba62e7",`

Then you can start building a request by instantiating an _POGOProtos\Networking\Envelopes\RequestEnvelope_. You'll need an AuthTicket and endpoint URL, you can receive that by sending a _POGOProtos\Networking\Envelopes\RequestEnvelope\AuthInfo_ with your token, set by `$env->setAuthInfo($auth)`. Add requests, like _GET_INVENTORY_ with `$env->addRequests`.

I could get into even more detail, but hopefully this helps you for now. You can also of course use a [full library](https://github.com/NicklasWallgren/PokemonGoAPI-PHP) (this one uses the "old" protobuf-plugin with most bugs fixed. Some implementations there are a lot different from the samples I posted here) if you don't want to build all that request/response/envelope/protobuf/auth/throttle/...-stuff from scratch and just get your Pokemon.

(I should probably move part of this to the wiki :laughing: )

**Comment by DrDelay** [comment]
Created something in the wiki: https://github.com/jaspervdm/pogoprotos-php/wiki/Usage
