### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by DrDelay** [jaspervdm/pogoprotos-php#16]
The submodule with the Protobuf-files ([AeonLucid/POGOProtos](https://github.com/AeonLucid/POGOProtos)) added the _GNU General Public License v3_ to his project, to be legally correct to further use it we should add a compatible license to this.

``` legal
All code linked with GPL 3.0 source code must be disclosed under a GPL 3.0 compatible license.
```

I was thinking about maybe BSD/MIT, what do you think @jaspervdm?

**Comment by jaspervdm** [comment]
Sure, lets go with MIT?

**Comment by jaspervdm** [comment]
I added the license file. This is my first time working on open source software. I'm not sure what to put as the copyright holders.  Feels kind of weird to put my (our) name(s) on it, since all we do is run someone elses script on the proto files that other people RE'd. Any modifications are welcomed :)

**Comment by DrDelay** [comment]
Yeah, technically we are not doing much. Still, I think it is correct to add the repos maintainers names.

Looking at [this license summary](https://tldrlegal.com/license/gnu-general-public-license-v3-%28gpl-3%29) I think we are good to go.

I "pimped" the [README](https://github.com/jaspervdm/pogoprotos-php/blob/73c2d8f046155f9922eeabbfed261f8fa28eb9ca/README.md) a bit, but nothing regarding the license. I added the standard ["educational use" BS disclosure](https://github.com/jaspervdm/pogoprotos-php/blob/73c2d8f046155f9922eeabbfed261f8fa28eb9ca/README.md#legal), don't know if it's worth something in case Niantic gets angry.
